## 부록2 넘파이 입문

### 라이브러리 임포트

In [1]:
# 라이브러리 임포트
import numpy as np

# 넘파이의 부동소수점 자릿수 표시
np.set_printoptions(suppress=True, precision=5)

### 정의

#### array 함수로 정의

In [2]:
# array 함수를 통한 벡터(1계 배열) 변수의 정의
n1 = np.array([1, 2, 3, 4, 5, 6, 7])

# 결과 확인
print(n1)

# 요소 수 확인
print(n1.shape)

# 또 다른 방법
print(len(n1))

[1 2 3 4 5 6 7]
(7,)
7


In [3]:
# array 함수를 통한 행렬(2계 배열) 변수의 정의
n2 = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9],
    [10,11,12]
])

# 결과 확인
print(n2)

# 요소 수 확인
print(n2.shape)

# 또 다른 방법
print(len(n2))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
4


#### zeros 함수, ones 함수 등을 사용

In [4]:
# zeros 함수로 모든 요소가 0인 벡터를 정의
n3 = np.zeros(5)

# 결과 확인
print(n3)

# 요소 수 확인
print(n3.shape)

[0. 0. 0. 0. 0.]
(5,)


In [5]:
# ones 함수로 모든 요소가 1인 행렬을 정의
n4 = np.ones((2,3))

# 결과 확인
print(n4)

# 요소 수 확인
print(n4.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [6]:
# 모든 요소가 정규 분포를 따르는 변수인 3계 행렬
n5 = np.random.randn(2,3,4)

# 결과 확인
print(n5)

# 요소 수 확인
print(n5.shape)

[[[ 0.35705 -1.04989 -0.58529  0.57153]
  [ 1.0679  -0.5711   2.3792   0.38826]
  [-0.8361   0.40919 -0.06052  0.09158]]

 [[ 1.56061  1.15909  0.09959 -0.14434]
  [-0.34591 -0.47816 -0.68424  1.55573]
  [ 0.76502  0.63429  1.31378 -1.44289]]]
(2, 3, 4)


#### 그래프 출력용 수치 배열 생성

In [7]:
# linspace 함수로 그래프 출력용 수치 배열을 계산

# 등간격으로 점을 찍음
# 점의 수가 세번째 인수
n6 = np.linspace(-1, 1, 11)

# 결과 확인
print(n6)

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]


In [8]:
# arange 함수를 사용한 그래프 출력용 수치 배열을 계산

# 등간격으로 점을 찍음
# 간격의 크기 값이 세번째 인수
# (두번째 인수는 max가 아니라 '미만'이라는 점에 주의)
n7 = np.arange(-1, 1.2, 0.2)

# 결과 확인
print(n7)

[-1.  -0.8 -0.6 -0.4 -0.2 -0.   0.2  0.4  0.6  0.8  1. ]


### 조작

#### 특정 행, 열의 추출

In [ ]:
# 원본 변수
print(n2)

# 모든 행의 0번째 열을 추출
n8 = n2[:,0]
print(n8)

In [9]:
# 첫번째 행과 세번째 행을 추출
# True / False 요소의 배열을 지정
n2_index = np.array([False, True, False, True])
n9 = n2[n2_index]
print(n9)

[[ 4  5  6]
 [10 11 12]]


#### reshape 함수

In [10]:
# 초기 변수 1계 배열
n10 = np.array(range(24))

# 결과 확인
print(n10)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [11]:
# 3x8의 2차원 배열로 변형
n11 = n10.reshape(3,8)

# 결과 확인
print(n11)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [12]:
# -1을 지정, 자동 계산
n12 = n10.reshape(2, -1, 4)

# 결과 확인
print(n12.shape)

(2, 3, 4)


In [13]:
# 벡터를 1행 N열의 행렬로 변형

# 원본 변수(1계 배열)
print(n10.shape)

# 변형
n13 = n10.reshape(1, -1)

# 결과 확인
print(n13.shape)

(24,)
(1, 24)


#### 축 교체하기

In [14]:
# 전치 행렬
print(n2)

n14 = n2.T
print(n14)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [15]:
# 축의 순서를 교체

# 원본 변수
print(n12.shape)
print(n12)

# 축을 (1, 2, 0) 순서로 교체
n15 = np.transpose(n12, (1, 2, 0))

# 결과 확인
print(n15.shape)
print(n15)

(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(3, 4, 2)
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


#### 행렬 연결하기

In [16]:
# 변수로 사용할 배열

# 2행 3열의 행렬
n16 = np.array(range(1,7)).reshape(2,3)
n17 = np.array(range(7,13)).reshape(2,3)

# 3요소 벡터
n18 = np.array(range(14,17))

# 2요소 벡터
n19 = np.array(range(17,19))

print(n16)
print(n17)
print(n18)
print(n19)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[14 15 16]
[17 18]


In [17]:
# 행렬과 행렬의 세로 연결
n20 = np.vstack([n16, n17])
print(n20)

# 행렬과 벡터의 세로 연결
n21 = np.vstack([n16, n18])
print(n21)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [14 15 16]]


In [18]:
# 행렬과 행렬의 가로 연결
n22 = np.hstack([n16, n17])
print(n22)

# 행렬과 벡터의 가로 연결
# 벡터의 shape를 (N, 1) 형태로 변형
n23 = n19.reshape(-1, 1)
n24 = np.hstack([n16, n23])
print(n24)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3 17]
 [ 4  5  6 18]]


### 연산

#### 넘파이 변수끼리의 연산

In [19]:
# 원본 변수
print(n16)
print(n17)

# 행렬간 연산
n25 = n16 + n17

# 결과 확인
print(n25)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 8 10 12]
 [14 16 18]]


#### 브로드캐스트 기능

In [20]:
# 브로드캐스트 기능

# 원본 변수
print(n1)

# 모든 요소에서 같은 값을 뺌
n22 = n1 - 4

# 결과 확인
print(n22)

[1 2 3 4 5 6 7]
[-3 -2 -1  0  1  2  3]


#### 유니버설 함수

In [21]:
# x 배열 준비
x = np.linspace(0, 2*np.pi, 25)
print(x)

# y=sin(x) 계산
y = np.sin(x)
print(y)

[0.      0.2618  0.5236  0.7854  1.0472  1.309   1.5708  1.8326  2.0944
 2.35619 2.61799 2.87979 3.14159 3.40339 3.66519 3.92699 4.18879 4.45059
 4.71239 4.97419 5.23599 5.49779 5.75959 6.02139 6.28319]
[ 0.       0.25882  0.5      0.70711  0.86603  0.96593  1.       0.96593
  0.86603  0.70711  0.5      0.25882  0.      -0.25882 -0.5     -0.70711
 -0.86603 -0.96593 -1.      -0.96593 -0.86603 -0.70711 -0.5     -0.25882
 -0.     ]


#### 집계 함수

In [22]:
# 집계 함수

print(f'원본 변수 : {n1}')

# 합 계산, sum 함수
n23 = np.sum(n1)
print(f'합 : {n23}')

# 평균 계산, mean 함수
n24 = np.mean(n1)
print(f'평균 : {n24}')

# 최댓값 계산, max 함수
n25 = np.max(n1)
print(f'최댓값 : {n25}')

# 최솟값 계산, min 함수
# 이런 방식도 가능
n26 = n1.min()
print(f'최솟값 : {n26}')

원본 변수 : [1 2 3 4 5 6 7]
합 : 28
평균 : 4.0
최댓값 : 7
최솟값 : 1


### 응용 예시

#### 두 변수를 비교해서 일치하는 개수로 정확도를 계산

In [23]:
# 2개의 넘파이 배열 준비
# 정답
yt = np.array([1, 1, 0, 1, 0, 1, 1, 0, 1, 1])
# 예측 값
yp = np.array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1])

# 내용 출력
print(yt)
print(yp)

[1 1 0 1 0 1 1 0 1 1]
[1 1 0 1 0 1 1 1 1 1]


In [24]:
# 배열의 각 요소를 동시에 비교함
matched = (yt == yp)
print(matched)

[ True  True  True  True  True  True  True False  True  True]


In [ ]:
# 이 결과에 sum 함수를 적용함
# 대상 변수가 논리형인 경우, True→1, False→0 으로 변환됨
# 정답 수를 세는 방법
correct = matched.sum()

# 전체 수는 len(matched)로 계산
total = len(matched)

# 정확도 계산
accuracy = correct/total

print(f'정답수 :{correct} 전체수 :{total} 정확도 :{accuracy:.3f}')

#### 벡터 값을 1차 함수로 변환해서 [0, 1] 범위로 제한

In [25]:
# 모든 값을 [0, 1] 범위에 포함하도록 변환

# 원본 변수
print(n1)

# 최댓값과 최솟값을 집계 함수로 얻음
n1_max = n1.max()
n1_min = n1.min()
print(n1_max, n1_min)

[1 2 3 4 5 6 7]
7 1


In [26]:
# 변환(브로드캐스트 기능 사용)
n27 = (n1 - n1_min) / (n1_max - n1_min)
print(n27)

[0.      0.16667 0.33333 0.5     0.66667 0.83333 1.     ]


#### 특정 조건을 만족하는 행을 추출

In [27]:
# n2의 0번째 열이 짝수임을 판단

# 원본 변수
print(n2)

n28 = n2[:,0] % 2 == 0

# 결과 확인
print(n28)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[False  True False  True]


In [28]:
# n28이 True인 행을 추출

n29 = n2[n28]

# 결과 확인
print(n29)

[[ 4  5  6]
 [10 11 12]]
